### ISSUE TITLE
`bluecap run capsule command -arg` is not processed correctly

### ISSUE THREAD

**Issue by bexelbie** [kirbyfan64/bluecap#1]
I noticed that the command arguments are interpreted by bluecap if they start with a dash (-) but otherwise are properly passed to the command being run.

BTW - I like where this is going, especially the export where this is not a bug.

This can be replicated in your dart example by doing

bluecap run dart pub -h

You will get the bluecap help, not pub help.

**Comment by refi64** [comment]
There's a way to do this in Python's argparse, but I'm eventually going to rewrite bluecap anyway (I love Python, but the startup times are a tad...long...). Meanwhile, you can use:

```
$ bluecap run dart -- pub -h
```

**Comment by bexelbie** [comment]
-- is perfectly acceptable and something I should have thought about.  Thank you.

**Comment by refi64** [comment]
New version on master handles this properly. There a few rough edges due to the way Nim's parseopt module works, but they're pretty rare and should be fixed by the time release comes.
